=== empowerplan/epp-app/digiplan/metadata/schema/population/schema.json
{
  "$id": "https://raw.githubusercontent.com/rl-institut/digiplan/main/digiplan/metadata/schema/v1-0-0",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "additionalProperties": false,
  "description": "JSON schema of a population forecast of a certain ABW municipality",
  "properties": {
    "language": {
      "description": "The used language in the JSON response values. Follows ISO 639-1. Example: en, de, fr, ...",
      "maxLength": 2,
      "minLength": 2,
      "title": "Language",
      "type": "string"
    },
    "lookup": {
      "description": "Lookup name used in the request as parameter. Example: ?lookup=population&municipality=12",
      "title": "Lookup Name",
      "type": "string"
    },
    "name": {
      "description": "Human-readable name of the JSON response",
      "title": "Human-Readable Name",
      "type": "string"
    },
    "payload": {
      "description": "A list of one or more municipality objects",
      "items": {
        "additionalProperties": false,
        "description": "Municipality object which contains a population time series list",
        "properties": {
          "description": {
            "description": "User facing short description for informational purposes",
            "maxLength": 280,
            "minLength": 0,
            "title": "Description",
            "type": "string"
          },
          "id": {
            "description": "Unique ID of the municipality",
            "title": "Id",
            "type": "integer"
          },
          "name": {
            "description": "Name of the municipality",
            "title": "Name",
            "type": "string"
          },
          "series": {
            "additionalProperties": false,
            "description": "Population time series object of one municipality with key value definition and items list",
            "properties": {
              "definition": {
                "additionalProperties": false,
                "description": "Key-value definition for lookup and human-readable names",
                "properties": {
                  "key": {
                    "additionalProperties": false,
                    "description": "Key lookup and name definition",
                    "properties": {
                      "lookup": {
                        "type": "string"
                      },
                      "name": {
                        "type": "string"
                      }
                    },
                    "required": [
                      "lookup",
                      "name"
                    ],
                    "title": "Key Definition",
                    "type": "object"
                  },
                  "value": {
                    "additionalProperties": false,
                    "description": "Value lookup and name definition",
                    "properties": {
                      "lookup": {
                        "type": "string"
                      },
                      "name": {
                        "type": "string"
                      }
                    },
                    "required": [
                      "lookup",
                      "name"
                    ],
                    "title": "Value Definition",
                    "type": "object"
                  }
                },
                "required": [
                  "key",
                  "value"
                ],
                "title": "Key-Value Definition",
                "type": "object"
              },
              "items": {
                "description": "Population list by year and number of inhabitants",
                "items": {
                  "inhabitants": {
                    "description": "The number of inhabitants",
                    "title": "Inhabitants",
                    "type": "integer"
                  },
                  "year": {
                    "description": "The year of a municipality's population",
                    "title": "Year",
                    "type": "integer"
                  }
                },
                "title": "Population by Year",
                "type": "array"
              }
            },
            "required": [
              "definition",
              "items"
            ],
            "title": "Population Time Series",
            "type": "object"
          }
        },
        "required": [
          "id",
          "name",
          "description",
          "series"
        ],
        "title": "Municipality",
        "type": "object"
      },
      "maxItems": 20,
      "minItems": 1,
      "title": "Population Forecast Municipalities List",
      "type": "array"
    }
  },
  "required": [
    "language",
    "lookup",
    "name",
    "payload"
  ],
  "title": "Population Forecast",
  "type": "object"
}

=== empowerplan/epp-app/digiplan/metadata/schema/population/example.json
{
  "language": "en",
  "lookup": "population",
  "name": "Population Forecast",
  "payload": [
    {
      "description": "The population in 2022 of Bitterfeld-Wolfen was 39,103 inhabitants. The entire ABW region had 370,190 inhabitants at that time. The following chart shows a forecast of the population development for the years 2022, 2030, and 2045.",
      "id": 2,
      "name": "Bitterfeld-Wolfen",
      "series": {
        "definition": {
          "key": {
            "lookup": "year",
            "name": "Year"
          },
          "value": {
            "lookup": "population",
            "name": "Population"
          }
        },
        "items": [
          {
            "key": 2022,
            "value": 39103
          },
          {
            "key": 2030,
            "value": 42212
          },
          {
            "key": 2045,
            "value": 45768
          }
        ]
      }
    },
    {
      "description": "The population in 2022 of Sandersdorf-Brehna was 14,468 inhabitants. The entire ABW region had 370,190 inhabitants at that time. The following chart shows a forecast of the population development for the years 2022, 2030, and 2045.",
      "id": 7,
      "name": "Sandersdorf-Brehna",
      "series": {
        "definition": {
          "key": {
            "lookup": "year",
            "name": "Year"
          },
          "value": {
            "lookup": "population",
            "name": "Population"
          }
        },
        "items": [
          {
            "key": 2022,
            "value": 14468
          },
          {
            "key": 2030,
            "value": 15132
          },
          {
            "key": 2045,
            "value": 14912
          }
        ]
      }
    },
    {
      "description": "The population in 2022 of Z\u00f6rbig was 9,311 inhabitants. The entire ABW region had 370,190 inhabitants at that time. The following chart shows a forecast of the population development for the years 2022, 2030, and 2045.",
      "id": 12,
      "name": "Z\u00f6rbig",
      "series": {
        "definition": {
          "key": {
            "lookup": "year",
            "name": "Year"
          },
          "value": {
            "lookup": "population",
            "name": "Population"
          }
        },
        "items": [
          {
            "key": 2022,
            "value": 9311
          },
          {
            "key": 2030,
            "value": 9182
          },
          {
            "key": 2045,
            "value": 8903
          }
        ]
      }
    }
  ]
}
