=== empowerplan/epp-app/digiplan/schemas/legend.schema.json
{
  "$id": "https://wam.rl-institut.de/digiplan/schemas/legend.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "additionalProperties": false,
  "description": "Legend payload",
  "properties": {
    "colors": {
      "description": "List of 6 colors",
      "items": {
        "description": "Color hex or rgb(a) value as string",
        "maxLength": 25,
        "type": "string"
      },
      "maxItems": 6,
      "minItems": 6,
      "type": "array",
      "uniqueItems": true
    },
    "title": {
      "description": "The title of the legend",
      "maxLength": 50,
      "type": "string"
    },
    "unit": {
      "description": "The unit name concerning the value range",
      "maxLength": 50,
      "type": "string"
    },
    "values": {
      "description": "List of 6 value range, e.g.: 0 - 1000, 1000 - 2000, ...",
      "items": {
        "description": "Value range",
        "maxLength": 25,
        "type": "string"
      },
      "maxItems": 6,
      "minItems": 6,
      "type": "array",
      "uniqueItems": true
    }
  },
  "required": [
    "title",
    "colors",
    "values"
  ],
  "type": "object"
}

=== empowerplan/epp-app/digiplan/schemas/legend.example.json
{
  "colors": [
    "#C3DCC5",
    "#A8CFAC",
    "#90C295",
    "#76AE7C",
    "#56955C",
    "#408147"
  ],
  "title": "Population",
  "unit": "population",
  "values": [
    "0 - 10.000",
    "10.000 - 20.000",
    "20.000 - 30.000",
    "30.000 - 40.000",
    "40.000 - 50.000",
    "50.000 - 60.000"
  ]
}
