=== empowerplan/epp-app/digiplan/schemas/popup.default.schema.json
{
  "$id": "https://wam.rl-institut.de/digiplan/schemas/popup.default.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "additionalProperties": false,
  "description": "The default JSON schema for use in popups on maps",
  "properties": {
    "application": {
      "description": "The application the concerning JSON is meant for.",
      "enum": [
        "popup"
      ],
      "title": "Application",
      "type": "string"
    },
    "chart": {
      "$ref": "atom.chart.example.json"
    },
    "language": {
      "description": "The used language. Follows ISO 639-1.",
      "enum": [
        "de",
        "en"
      ],
      "title": "Language",
      "type": "string"
    },
    "lookup": {
      "description": "Lookup name used in the request. Example: ?lookup=<lookup_name>&municipality=12",
      "title": "Lookup Name",
      "type": "string"
    },
    "name": {
      "description": "Human-readable name. Used in popup heading",
      "title": "Human-Readable Name",
      "type": "string"
    },
    "sources": {
      "description": "List of data sources",
      "items": {
        "additionalProperties": false,
        "description": "Name and identifier of data source",
        "properties": {
          "iri": {
            "description": "identifier can be either URI or IRI (IRI is superset of URI). More info: https://json-schema.org/understanding-json-schema/reference/string.html#id7",
            "format": "iri",
            "type": "string"
          },
          "name": {
            "type": "string"
          }
        },
        "required": [
          "name",
          "iri"
        ],
        "title": "Source Item",
        "type": "object"
      },
      "maxItems": 20,
      "minItems": 1,
      "title": "Sources",
      "type": "array"
    }
  },
  "required": [
    "application",
    "chart",
    "language",
    "lookup",
    "name",
    "sources"
  ],
  "title": "Popup Default Schema",
  "type": "object"
}

=== empowerplan/epp-app/digiplan/static/tests/api/popup.json
{
  "application": "popup",
  "chart": {
    "chartType": "bar",
    "payload": [
      {
        "data": {
          "definition": {
            "key": {
              "lookup": "year",
              "name": "Year",
              "type": "integer"
            },
            "value": {
              "lookup": "population",
              "name": "Population",
              "type": "integer"
            }
          },
          "series": [
            {
              "key": 2022,
              "value": 9311
            },
            {
              "key": 2030,
              "value": 9182
            },
            {
              "key": 2045,
              "value": 8903
            }
          ]
        },
        "description": "The population in 2022 of Z\u00f6rbig was 9,311 inhabitants. The entire ABW region had 370,190 inhabitants at that time. The following chart shows a forecast of the population development for the years 2022, 2030, and 2045.",
        "id": 12,
        "name": "Z\u00f6rbig"
      }
    ]
  },
  "language": "en",
  "lookup": "population",
  "name": "Population Forecast",
  "sources": [
    {
      "iri": "https://wam.rl-institut.de/digiplan/sources#11",
      "name": "Bev\u00f6lkerungz\u00e4hlung Anhalt, 2021"
    },
    {
      "iri": "https://wam.rl-institut.de/digiplan/sources#12",
      "name": "Bev\u00f6lkerungsprognose Anhalt, 2030"
    },
    {
      "iri": "https://wam.rl-institut.de/digiplan/sources#13",
      "name": "Bev\u00f6lkerungsprognose Anhalt, 2050"
    }
  ]
}
